### ISSUE TITLE
Error when using with Eclipse Installer

### ISSUE THREAD

**Issue by andham** [gratex/oomph-task-server#2]
I've followed the instructions and get the following error when Eclipse Installer v1.7.0 tries to installed the extended task:

> org.eclipse.core.runtime.CoreException: Cannot complete the install because one or more required items could not be found.
	at org.eclipse.oomph.util.OomphPlugin.coreException(OomphPlugin.java:280)
	at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:425)
	at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:337)
	at org.eclipse.oomph.setup.ui.EnablementComposite$5.run(EnablementComposite.java:316)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Contains: Software being installed: artificial_root 1.0.0.v1496140089499
Contains: Missing requirement: Server Setup Task 1.0.0.201703161243 (com.gratex.oomph.task.server 1.0.0.201703161243) requires 'bundle com.google.guava 0.0.0' but it could not be found
Contains: Cannot satisfy dependency:
Contains: From: artificial_root 1.0.0.v1496140089499
Contains: To: com.gratex.oomph.task.server.feature.feature.group 0.0.0
Contains: Cannot satisfy dependency:
Contains: From: Server Setup Task 1.0.0.201703161243 (com.gratex.oomph.task.server.feature.feature.group 1.0.0.201703161243)
Contains: To: com.gratex.oomph.task.server [1.0.0.201703161243]

**Comment by andham** [comment]
I asked on this in the oomph forum and apparently there are many dependencies, which are not included.

See answer in https://www.eclipse.org/forums/index.php?t=msg&th=1086494&goto=1764499&#msg_1764499

**Comment by andham** [comment]
Please also see #3 which is related to this.

**Comment by andham** [comment]
I believe this should not be an issue now as #3 has been fixed.
