### ISSUE TITLE
WAS 8.5 doesn't work

### ISSUE THREAD

**Issue by andham** [gratex/oomph-task-server#4]
I get the following exception when trying to configure a WAS 8.5 instance:

> Performing Websphere Server Task WebSphere Application Server traditional V8.5.5 at localhost
Updating build paths
java.lang.NoClassDefFoundError: com/ibm/ws/ast/st/v7/core/internal/WASServer
  at com.gratex.oomph.task.server.creator.impl.WebsphereServerCreator.configureWas85(WebsphereServerCreator.java:223)
  at com.gratex.oomph.task.server.creator.impl.WebsphereServerCreator.createServerInstanceInternal(WebsphereServerCreator.java:159)
  at com.gratex.oomph.task.server.creator.ServerCreator.createServerInstance(ServerCreator.java:61)
  at com.gratex.oomph.task.server.impl.WebsphereServerTaskImpl.perform(WebsphereServerTaskImpl.java:617)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4488)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4482)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4480)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3258)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:567)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:693)
  at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.lang.ClassNotFoundException: com.ibm.ws.ast.st.v7.core.internal.WASServer cannot be found by com.gratex.oomph.task.server_1.0.0.201705310831
  at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:461)
  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:372)
  at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:364)
  at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:161)
  at java.lang.ClassLoader.loadClass(Unknown Source)
  at com.gratex.oomph.task.server.creator.impl.WebsphereServerCreator.configureWas85(WebsphereServerCreator.java:223)
  at com.gratex.oomph.task.server.creator.impl.WebsphereServerCreator.createServerInstanceInternal(WebsphereServerCreator.java:159)
  at com.gratex.oomph.task.server.creator.ServerCreator.createServerInstance(ServerCreator.java:61)
  at com.gratex.oomph.task.server.impl.WebsphereServerTaskImpl.perform(WebsphereServerTaskImpl.java:617)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:3324)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.access$1(SetupTaskPerformer.java:3267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil$1.run(SetupTaskPerformer.java:4488)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
  at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.performNeededSetupTasks(SetupTaskPerformer.java:4482)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer$WorkspaceUtil.access$0(SetupTaskPerformer.java:4480)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:3258)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:3233)
  at org.eclipse.oomph.setup.internal.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:3133)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9.run(ProgressPage.java:567)
  at org.eclipse.oomph.setup.ui.wizards.ProgressPage$11$1.run(ProgressPage.java:693)
  ... 1 more

I'm using version 1.0.14.

**Comment by koval-jan** [comment]
I've found the problem. Please try new version 1.0.15

**Comment by andham** [comment]
Yes, now it works. Great!
